### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by gnestor** [jupyterlab/jupyterlab-monaco#17]
Is it time to publish this extension to npm?

**Comment by jasongrout** [comment]
Yes. Do you feel comfortable doing so? Do you want permissions to do so?

**Comment by gnestor** [comment]
Sure. I think I might because I have access to the jupyterlab org on npm. Do we want to publish as jupyterlab-monaco or @jupyterlab/monaco, or @jupyterlab/monaco-extension?

**Comment by jasongrout** [comment]
Oh right, I forgot we never published this. It's still, of course, *very* experimental, but on the other hand, some people have appreciated having it.

Let me take a look at what I think would be a good first cut of features before we initially publish this.

**Comment by gnestor** [comment]
I agree that it's a great extension, I've been using it in lieu of the default file editor. I will help with future development, publishing, etc. 👍

**Comment by nabriis** [comment]
Is it getting published?

**Comment by gnestor** [comment]
I just reviewed the open issues on this repo and it looks like [there are some jupyterlab monaco extensions for other jupyterlab-based apps that offer LSP integration and monaco in notebook code cells](https://github.com/jupyterlab/jupyterlab-monaco/issues/19), so maybe we should wait to add these features before publishing this package? Or we can just publish now that it's stable...

**Comment by TiemenSch** [comment]
I'd say that it would help to get some traction just by publishing what there already is!

**Comment by dhirschfeld** [comment]
Maybe merge #22 (if it's ready to go now) then publish?

**Comment by fcollonval** [comment]
@dhirschfeld I'ld love to get my PR merged. But there is a packaging issue due to monaco-languageclient 0.9.0. A alias for a simplified vscode package should be passed to webpack. For building the extension it is easy. But for jupyterlab I don't know how to do it with out touching the standard webpack.config shipped with jupyterlab.
Maybe @gnestor or @jasongrout have some ideas?

**Comment by gnestor** [comment]
@fcollonval Excellent work on #22!! I don't fully understand your packaging issue. Can you give me an idea of what webpack config would need to change?

One way around webpack issues in general is to append scripts to the DOM. I have done this in other projects to get monaco editor working when webpack isn't exactly configurable. Not sure if this relevant to you issue...
