### ISSUE TITLE
Another implementation of monaco in jupyterlab

### ISSUE THREAD

**Issue by lzfxxx** [jupyterlab/jupyterlab-monaco#19]
[R-Brain/jupyterlab](https://github.com/R-Brain/jupyterlab/blob/master/packages/monaco-extension/src/index.ts) has a implementation of `monaco` on jupyterlab, but on a very old version.

Depending on my experience on their [website](https://r-brain.io/), their implementation is quite good, they even integrated `monaco` into the notebook cells. So I think this might be a help even it's old.

**Comment by dhirschfeld** [comment]
Also https://github.com/theia-ide/theia

**Comment by nabriis** [comment]
Theia looks awesome!
